spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 8766

eureka:
  client:
    serviceUrl:
#      todo euraka 服务之中心的地址
      defaultZone: http://localhost:8761/eureka/

# todo 打开feign中的熔断器
feign:
  hystrix:
    enabled: true
